---
- name: Update Programs
  hosts: teste
  tasks:
    - name: Configure Chocolatey Source
      win_chocolatey_source:
        name: community
        state: present
        source: https://community.chocolatey.org/api/v2/

    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present
