- name: Update programas
  hosts: teste
  tasks:
    - name: Ensure Chocolatey installed from internal repo
      win_chocolatey:
        name: chocolatey
        state: present
        source:  https://community.chocolatey.org/api/v2/
   
    - name: Remove Remote Desktop Manager
      ansible.windows.win_package:
        path: https://github.com/glpi-project/glpi-agent/releases/download/1.5/GLPI-Agent-1.5-x64.msi
        state: absent
